### ISSUE TITLE
在模型的验证中出现了以下问题，应怎样解决呢？ 谢谢！ValueError: only one element tensors can be converted to Python scalars

### ISSUE THREAD

**Issue by lifafang** [jingtianyilong/YOLOv4-pytorch#11]
Val batch:   0%|          | 0/12 [00:06<?, ?imgs/s]
Traceback (most recent call last):
  File "/home/桌面/YOLOv4-pytorch/train.py", line 260, in <module>
    Trainer(log_dir,resume= args.resume).train()
  File "/home/桌面/YOLOv4-pytorch/train.py", line 171, in train
    coco_stat = evaluator.evaluate(self.yolov4)
  File "/home/桌面/YOLOv4-pytorch/eval/cocoapi_evaluator.py", line 61, in evaluate
    info_img = [float(info) for info in info_img]
  File "/home/桌面/YOLOv4-pytorch/eval/cocoapi_evaluator.py", line 61, in <listcomp>
    info_img = [float(info) for info in info_img]
**ValueError: only one element tensors can be converted to Python scalars**

**Comment by lifafang** [comment]
已解决，thx

**Comment by lifafang** [comment]
@jingtianyilong @

**Comment by kimsjpk1** [comment]
you should validation parameter: batch size is 1. change validation batch size parameter
